title: Sander Noels
theme: jekyll-theme-cayman
description: Browse through my personal universe.
show_downloads: true

github:
  url: https://github.com/snoels
  name: snoels

linkedin:
  url: https://www.linkedin.com/in/sander-noels-79411815a/

page:
  contact: https://snoels.github.io/contact.html
  publications: https://snoels.github.io/publications.html
  about: https://snoels.github.io/about.html

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

header_page_refs: ['contact', 'publications']
